### ISSUE TITLE
Post bodies that are too long are rejected by the forum

### ISSUE THREAD

**Issue by chief1983** [scp-fs2open/nightlybuild#30]
This generally happens when the git log is too long.  When we detect an overly long log, we should attempt to link to the log set on Github instead of including it in the body.  We could probably have the link all the time and only include the contents when they are short enough to fit within the forum limit (to be determined what that limit is).

**Comment by Goober5000** [comment]
Has this been fixed?

**Comment by asarium** [comment]
No, as far as I know there has been no progress on this.

**Comment by JohnAFernandez** [comment]
Since we just have a place holder and manually write a curated change log, this is no longer an issue.
