### ISSUE TITLE
Nightly builds should be updated in the FSO Installer repository

### ISSUE THREAD

**Issue by Goober5000** [scp-fs2open/nightlybuild#38]
Just as release builds are available, the latest nightly build should be available too.  This was requested on Discord.

**Comment by asarium** [comment]
There is some rudimentary support for outputting the release build information in the format for the installer but there is no automatic support for uploading that to the relevant servers for making the builds available.

**Comment by Goober5000** [comment]
Probably no longer needed at this point.
